[package]
name = "agent-edge-rs"
version = "0.1.0"
edition = "2024"
authors = ["Fredrik Skogberg <freskog@gmail.com>"]
description = "Wakeword-only edge client for low-powered devices"

[dependencies]
# Core utilities
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.5", features = ["derive"] }

# Machine learning
tflitec = "0.6.0"

# Global state management
lazy_static = "1.4"

# PulseAudio support (Linux only)
[target.'cfg(target_os = "linux")'.dependencies]
libpulse-binding = { version = "2.28", optional = true }
libpulse-simple-binding = { version = "2.28", optional = true }

[[bin]]
name = "agent-edge"
path = "src/main.rs"
[features]
default = []
pulse = ["libpulse-binding", "libpulse-simple-binding"]

# Profile optimized for static linking
[profile.release-static]
inherits = "release"
lto = true
codegen-units = 1
panic = "abort"
