[package]
name = "agent-edge-rs"
version = "0.1.0"
edition = "2021"
authors = ["Fredrik Skogberg <freskog@gmail.com>"]
description = "Wakeword-only edge client for low-powered devices"

[dependencies]
# Audio capture and processing (cross-platform)
cpal = "0.15"  # Latest version with excellent cross-platform support
dasp = "0.11"  # Digital Audio Signal Processing, includes sample conversion

# TensorFlow Lite inference (temporarily disabled for Phase 1)
# tflite = "0.9"  # Latest stable version compatible with openwakeword models

# Audio processing and signal analysis
hound = "3.5"  # For WAV file handling during testing
byteorder = "1.5"

# Utilities
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"  # Latest version for better logging
clap = { version = "4.5", features = ["derive"] }  # Latest version with great CLI support

# Cross-platform async runtime
tokio = { version = "1.0", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
# PulseAudio support only on Linux (Raspberry Pi)
libpulse-binding = { version = "2.30", optional = true }
libpulse-simple-binding = { version = "2.29", optional = true }

[features]
default = []
# Direct PulseAudio support for better latency control (Linux only)
pulseaudio = ["libpulse-binding", "libpulse-simple-binding"]

[dev-dependencies]
tempfile = "3.8"

# Cross-compilation targets
[target.'cfg(target_arch = "aarch64")']
[target.'cfg(target_arch = "arm")']

[[bin]]
name = "agent-edge"
path = "src/main.rs" 