[package]
name = "agent-edge-rs"
version = "0.1.0"
edition = "2024"
authors = ["Fredrik Skogberg <freskog@gmail.com>"]
description = "Wakeword-only edge client for low-powered devices"

[dependencies]
# Core utilities
log = "0.4"
thiserror = "2.0.10"
env_logger = "0.11.8"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }

# Machine learning
tflitec = "0.6.0"

# Voice Activity Detection
webrtc-vad = "0.4.0"

# Global state management
lazy_static = "1.4"

# PulseAudio support (Linux only)
[target.'cfg(target_os = "linux")'.dependencies]
libpulse-binding = "2.0"
libpulse-simple-binding = "2.0"

[dev-dependencies]
hound = "3.5"

[[bin]]
name = "agent-edge"
path = "src/main.rs"
