[package]
name = "service-protos"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.13"
prost = "0.13"
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.13"
prost-build = "0.13"
