[target.aarch64-unknown-linux-gnu]
# Raspberry Pi AArch64 (3/Zero 2W/4/5) with 64-bit Raspberry OS Lite
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-apple-darwin]
# Native compilation on Apple Silicon (development)

[build]
# Primary targets: macOS ARM64 (dev) + Raspberry Pi AArch64 (prod)
# target = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu"] 