[package]
name = "wakeword"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "OpenWakeWord detection library using TensorFlow Lite"
license.workspace = true

[lib]
name = "wakeword"
path = "src/lib.rs"

[[bin]]
name = "wakeword"
path = "src/main.rs"

[features]
default = ["xnnpack", "xnnpack_qs8"]
xnnpack = ["tflitec/xnnpack"]
xnnpack_qs8 = ["tflitec/xnnpack_qs8"]

[dependencies]
audio_api = { path = "../audio_api" }

# TensorFlow Lite (with XNNPACK)
tflitec = { version = "0.6.0", features = ["xnnpack", "xnnpack_qs8"] }

# Core functionality
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
cpal = "0.16"
dotenvy = "0.15"
env_logger = "0.10"
hound = "3.5"
libc = "0.2"
log = "0.4"
num-traits = "0.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.26", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
tempfile = "3.0"


[build-dependencies]
cc = "1.0"
